#!/usr/bin/env bash

disconnected=""
wireless_connected=""
ethernet_connected=""
usb_connected=""

ID="$(ip link | grep 'state UP')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; 
            sleep 1
            if [[ $ID == w* ]]; then
                echo "$wireless_connected" ;
                sleep 1
            fi
        else
            echo "$usb_connected" ;
            sleep 1
        fi
    else
        echo "$disconnected" ;
        sleep 1
    fi
done
